routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\CompanyController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::resource('companies', CompanyController::class)->except('show');
    Route::resource('clients', ClientController::class)->except('show');
});

app/Models/Company.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int id
 * @property string name
 * @property string slug
 * @property string address
 * @property int client_id
 * @property Carbon|string created_at
 * @property Carbon|string updated_at
 *
 * @property Client client
 *
 * Class Company
 * @package App\Models
 */
class Company extends Model
{
    use HasFactory;

    /** @var array $fillable */
    protected $fillable = [
        'name',
        'address',
        'client_id',
    ];

    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Company\CompanyGetRequest;
use App\Http\Resources\Company\CompanyCollection;
use App\Http\Resources\Company\CompanyWithoutClientCollection;
use App\Models\Client;
use App\Services\CompanyService;
use Illuminate\Http\JsonResponse;

class CompanyController extends Controller
{
    public function __construct(private CompanyService $companyService) {}

    public function getCompanies(CompanyGetRequest $request): JsonResponse
    {
        return response()->json(new CompanyCollection($this->companyService->getAll($request->all())));
    }

    public function getCompaniesByClient(Client $client, CompanyGetRequest $request): JsonResponse
    {
        return response()
            ->json(
                new CompanyWithoutClientCollection(
                    $this
                        ->companyService
                        ->getCompaniesByClient(
                            $client,
                            $request->all()
                        )
                )
            )
        ;
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Company\CompanyGetRequest;
use App\Http\Requests\Company\CompanyStoreRequest;
use App\Http\Requests\Company\CompanyUpdateRequest;
use App\Models\Company;
use App\Services\ClientService;
use App\Services\CompanyService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CompanyController extends Controller
{
    public function __construct(
        private CompanyService $companyService,
        private ClientService $clientService,
    ) {}

    public function index(CompanyGetRequest $request): View
    {
        $companies = $this->companyService->getAll($request->all());

        return view('cms.company.index', ['companies' => $companies]);
    }

    public function create(): View
    {
        $company = new Company();
        $clients = $this->clientService->getClientsWithoutPaginate();

        return view('cms.company.create', [
            'company' => $company,
            'clients' => $clients,
        ]);
    }

    public function store(CompanyStoreRequest $request): RedirectResponse
    {
        $isCreated = $this->companyService->create($request->getDto());

        if ($isCreated) {
            return redirect()->route('companies.index');
        }

        return redirect()->back();
    }

    public function edit(Company $company): View
    {
        $clients = $this->clientService->getClientsWithoutPaginate();

        return view('cms.company.edit', [
            'company' => $company,
            'clients' => $clients,
        ]);
    }

    public function update(CompanyUpdateRequest $request, Company $company): RedirectResponse
    {
        $isUpdated = $this->companyService->update($company, $request->getDto());

        if ($isUpdated) {
            return redirect()->route('companies.index');
        }

        return redirect()->back();
    }

    public function destroy(Company $company): RedirectResponse
    {
        $isDeleted = $this->companyService->delete($company);

        if ($isDeleted) {
            return redirect()->route('companies.index');
        }

        return redirect()->back();
    }
}

resources/views/cms/company/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Create new category</h3>
        </div>
        <div class="card-body">
            <form action="{{ route('companies.store') }}" method="post">
                @csrf
                @include('cms.company.form.form')
                <button type="submit" class="btn btn-primary">Create</button>
                <button type="reset" class="btn btn-warning">Cancel</button>
            </form>
        </div>
    </div>
@endsection

resources/views/cms/company/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Update category {{ $company->name ?? '' }}</h3>
        </div>
        <div class="card-body">
            <form action="{{ route('companies.update', $company) }}" method="post">
                @csrf
                @method('put')
                @include('cms.company.form.form')
                <button type="submit" class="btn btn-primary">Update</button>
                <button type="reset" class="btn btn-warning">Cancel</button>
            </form>
        </div>
    </div>
@endsection

resources/views/cms/company/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card-body">
        <div class="row">
            <div class="col">
                <h1>Categories</h1>
            </div>
            <div class="mb-3">
                <a
                    type="button"
                    class="btn btn-primary"
                    href="{{ route('companies.create') }}"
                >
                    Add Category
                </a>
            </div>
            <table
                    class="table table-bordered table-hover dataTable dtr-inline"
                    role="grid"
            >
                <thead>
                    <tr role="row">
                        <th>ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Address</th>
                        <th>Client</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($companies as $company)
                        @php /** @var App\Models\Company $company **/ @endphp
                        <tr>
                            <th>
                                {{ $company->id }}
                            </th>
                            <th>
                                <a href="{{ route('companies.edit', $company) }}">{{ $company->name }}</a>
                            </th>
                            <th>
                                {{ $company->slug }}
                            </th>
                            <th>
                                {{ $company->address }}
                            </th>
                            <th>
                                {{ $company->client->full_name }}
                            </th>
                            <th>
                                {{ $company->created_at }}
                            </th>
                            <th>
                                {{ $company->updated_at ?? '' }}
                            </th>
                            <th class="text-right">
                                <form
                                    onsubmit="return confirm('Delete category?');"
                                    action="{{ route('companies.destroy', $company) }}"
                                    method="post"
                                >
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                </form>
                            </th>
                        </tr>
                    @empty
                        <tr>
                            <th colspan="3">No data</th>
                        </tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3" class="dataTables_paginate paging_simple_numbers"> {{ $companies->links() }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection