routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\CompanyController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::resource('companies', CompanyController::class)->except('show');
    Route::resource('clients', ClientController::class)->except('show');
});

app/Models/Client.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Collection;

/**
 * @property int id
 * @property string first_name
 * @property string last_name
 * @property string full_name
 * @property Carbon|string created_at
 * @property Carbon|string updated_at
 *
 * @property Collection|Company[] companies
 *
 * Class Client
 * @package App\Models
 */
class Client extends Model
{
    use HasFactory;

    /** @var array $fillable */
    protected $fillable = [
        'first_name',
        'last_name',
    ];

    public function getFullNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function companies(): HasMany
    {
        return $this->hasMany(Company::class);
    }
}

app/Http/Controllers/Api/ClientController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Client\ClientGetRequest;
use App\Http\Resources\Client\ClientCollection;
use App\Services\ClientService;
use Illuminate\Http\JsonResponse;

class ClientController extends Controller
{
    public function __construct(private ClientService $clientService) {}

    public function getClients(ClientGetRequest $request): JsonResponse
    {
        return response()->json(new ClientCollection($this->clientService->getAll($request->all())));
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Client\ClientRequest;
use App\Models\Client;
use App\Services\ClientService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ClientController extends Controller
{
    public function __construct(private ClientService $clientService) {}

    public function index(): View
    {
        $clients = $this->clientService->getAll();

        return view('cms.client.index', ['clients' => $clients]);
    }

    public function create(): View
    {
        $client = new Client();

        return view('cms.client.create', [
            'client' => $client,
        ]);
    }

    public function store(ClientRequest $request): RedirectResponse
    {
        $isCreated = $this->clientService->create($request->getDto());

        if ($isCreated) {
            return redirect()->route('clients.index');
        }

        return redirect()->back();
    }

    public function edit(Client $client): View
    {
        return view('cms.client.edit', [
            'client' => $client,
        ]);
    }

    public function update(ClientRequest $request, Client $client): RedirectResponse
    {
        $isUpdated = $this->clientService->update($client, $request->getDto());

        if ($isUpdated) {
            return redirect()->route('clients.index');
        }

        return redirect()->back();
    }

    public function destroy(Client $client): RedirectResponse
    {
        $isDeleted = $this->clientService->delete($client);

        if ($isDeleted) {
            return redirect()->route('clients.index');
        }

        return redirect()->back();
    }
}

resources/views/cms/client/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Create new client</h3>
        </div>
        <div class="card-body">
            <form action="{{ route('clients.store') }}" method="post">
                @csrf
                @include('cms.client.form.form')
                <button type="submit" class="btn btn-primary">Create</button>
                <button type="reset" class="btn btn-warning">Cancel</button>
            </form>
        </div>
    </div>
@endsection

resources/views/cms/client/edit.blade.php
@extends('adminlte::page')

@php /** @var App\Models\Client $client */ @endphp
@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Update client {{ $client->first_name ?? '' }}</h3>
        </div>
        <div class="card-body">
            <form action="{{ route('clients.update', $client) }}" method="post">
                @csrf
                @method('put')
                @include('cms.client.form.form')
                <button type="submit" class="btn btn-primary">Update</button>
                <button type="reset" class="btn btn-warning">Cancel</button>
            </form>
        </div>
    </div>
@endsection

resources/views/cms/client/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card-body">
        <div class="row">
            <div class="col">
                <h1>Clients</h1>
            </div>
            <div class="mb-3">
                <a
                    type="button"
                    class="btn btn-primary"
                    href="{{ route('clients.create') }}"
                >
                    Add Client
                </a>
            </div>
            <table
                    class="table table-bordered table-hover dataTable dtr-inline"
                    role="grid"
            >
                <thead>
                    <tr role="row">
                        <th>ID</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Companies</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($clients as $client)
                        @php /** @var App\Models\Client $client **/ @endphp
                        <tr>
                            <th>
                                {{ $client->id }}
                            </th>
                            <th>
                                <a href="{{ route('clients.edit', $client) }}">{{ $client->first_name }}</a>
                            </th>
                            <th>
                                {{ $client->last_name }}
                            </th>
                            <th>
                                {{ $client->companies->pluck('name')->implode(', ') }}
                            </th>
                            <th>
                                {{ $client->created_at }}
                            </th>
                            <th>
                                {{ $client->updated_at ?? '' }}
                            </th>
                            <th class="text-right">
                                <form
                                    onsubmit="return confirm('Delete category?');"
                                    action="{{ route('clients.destroy', $client) }}"
                                    method="post"
                                >
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                </form>
                            </th>
                        </tr>
                    @empty
                        <tr>
                            <th colspan="3">No data</th>
                        </tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3" class="pagination"> {{ $clients->links() }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection